name: Makefile LaTeX CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y latexmk texlive-xetex texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
    - name: Install Thai fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-thai-tlwg fonts-tlwg-laksaman-ttf fonts-tlwg-garuda-ttf fonts-inconsolata

    - name: Build PDF with Makefile
      run: make

    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
          name: pdf-output
          path: report.pdf
